apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-connect-gateway
  namespace: dev-connect
  labels:
    app.kubernetes.io/name: dev-connect-gateway
    app.kubernetes.io/part-of: dev-connect
automountServiceAccountToken: false

