apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dev-connect-gateway.fullname" . }}-haproxy
  labels:
    app.kubernetes.io/name: {{ include "dev-connect-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Values.target.name }}
    app.kubernetes.io/part-of: dev-connect
data:
  haproxy.cfg: |
    global
      log stdout format raw local0

    defaults
      mode tcp
      log global
      timeout connect 10s
      timeout client 12h
      timeout server 12h
      option tcplog

    frontend ssh
      bind :2222
      default_backend target

{{- if and .Values.monitoring.enabled .Values.monitoring.metrics.enabled }}
    frontend metrics
      mode http
      bind :{{ .Values.monitoring.metrics.port }}
      http-request use-service prometheus-exporter if { path {{ .Values.monitoring.metrics.path }} }
      no log

{{- end }}
    backend target
      server {{ .Values.target.name }} {{ .Values.target.host }}:{{ .Values.target.port }} check
