apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dev-connect-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dev-connect-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Values.target.name }}
    app.kubernetes.io/part-of: dev-connect
automountServiceAccountToken: false

