apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-connect-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dev-connect-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Values.target.name }}
    app.kubernetes.io/part-of: dev-connect
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "dev-connect-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Values.target.name }}
  ports:
    - name: ssh
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 2222
{{- if and .Values.monitoring.enabled .Values.monitoring.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.monitoring.metrics.port }}
{{- end }}
